### ISSUE TITLE
secondary calculation backend in Rust w/ Fuzzing and Kani testing a-la Ethereum client diversity

### ISSUE THREAD

**Issue by vacekj** [gitcoinco/grants-stack-indexer#76]
https://model-checking.github.io/kani/
Points: 3

**Comment by boudra** [comment]
this is probably more relevant for Pluralistic.js no?

Either way looks like there's a property testing library for TS that could be useful to implement some fuzz tests: https://github.com/dubzzz/fast-check

@gravityblast

**Comment by vacekj** [comment]
In light of recent indexer bugs, I would say it would be worth it to do both. 
Agree to try out fast-check too.

**Comment by boudra** [comment]
@vacekj do you mind being more specific? what kind of bugs are you looking to fix and how will fuzzy testing will help us more than normal tests?

I agree having a second implementation of linear QF can be beneficial to catch any mistakes. Fuzzy testing can be a powerful tool but I am unsure how it applies to this case, since running calculations with a bunch of random data doesn't tell us much of whether the calculation is correct or not.

**Comment by vacekj** [comment]
I would say for Linear QF it would help identify edge cases. I also think it wouldn't be too hard to set it up, for both pluralistic.js using fast-check and for an alternative rust impl using Kani or similar.

**Comment by bard** [comment]
@vacekj doing some issue gardening, is this still relevant / something we want to work on?

**Comment by vacekj** [comment]
@gravityblast Not priority, but would like to get this done for at least pluralistic.js and the main calculator in indexer. If not part of work, at least on my personal time.
